grammar: Add constructors
vsl-lang/VSL pull request #35
Opened 2017-06-15 23:31 UTC by CrazyGuy108

### I have:
 - [x] Ran a test (`npm run dev && npm test`)
 - [x] Added tests for my changes
 - [x] Documented my code thoroughly.

2017-06-15 23:34 UTC, vihanb requested changes
Looks good, just the one thing with `get children()`

2017-06-15 23:34 UTC, vihanb commented on src/vsl/parser/nodes/constructor.js
> +        return ['access', 'optional', 'params', 'statements'];
children only should return child `Node` object so `access` and `optional` shouldn't be here.

2017-06-15 23:35 UTC, vihanb commented
Random Thought: do we want to reserve `self` and `super`. That way we could prevent stupid thing like `func self(){}` from hapenning.

2017-06-15 23:37 UTC, CrazyGuy108 commented
@vihanb imo I would leave that to something that isn't the parser.

2017-06-16 00:05 UTC, vihanb approved these changes

2017-06-16 00:06 UTC, merged